name: Feature Request
description: Suggest an idea for this project
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Important: Before Creating an Issue
        Please check if a similar feature request already exists by following these steps:
        1. Search [existing issues](https://github.com/tsuyoshi-otake-system-exe-jp/otak-monitor/issues)
        2. Check both "Open" and "Closed" issues
        3. Search with similar keywords

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: I have checked existing issues and confirmed no similar requests exist
          required: true
        - label: I have checked the latest extension features
          required: true

  - type: input
    id: vscode-version
    attributes:
      label: Visual Studio Code Version
      description: Please specify your VSCode version
      placeholder: "e.g., 1.85.1"
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: Otak Monitor Extension Version
      description: Please specify the extension version
      placeholder: "e.g., 1.1.1"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Related Problem
      description: Please describe the problem or inconvenience related to this feature request
      placeholder: "e.g., Currently, it's not possible to monitor specific processes only"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Please describe your proposed feature in detail
      placeholder: "e.g., Add ability to select which processes to monitor"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Please describe any alternative solutions you've considered
      placeholder: "e.g., Considered specifying process names in settings file but..."
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context or references about the feature request
    validations:
      required: false